services:
  # Next.js instances (for load balancing)
  nextjs-app-instance1:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXT_PUBLIC_SUPABASE_URL=https://vyhxpbndpwokyybzmugb.supabase.co
      - NEXT_PUBLIC_SUPABASE_KEY=your_supabase_key
    depends_on:
      - redis

  nextjs-app-instance2:
    build:
      context: .
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXT_PUBLIC_SUPABASE_URL=https://vyhxpbndpwokyybzmugb.supabase.co
      - NEXT_PUBLIC_SUPABASE_KEY=your_supabase_key
    depends_on:
      - redis

  nextjs-app-instance3:
    build:
      context: .
    ports:
      - "3003:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXT_PUBLIC_SUPABASE_URL=https://vyhxpbndpwokyybzmugb.supabase.co
      - NEXT_PUBLIC_SUPABASE_KEY=your_supabase_key
    depends_on:
      - redis

  # Redis service
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  # Nginx load balancer
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs-app-instance1
      - nextjs-app-instance2
      - nextjs-app-instance3
    
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    ports:
    - "9113:9113"
    environment:
    - NGINX_HOST=http://nginx
    - NGINX_PORT=80
    command: ["-nginx.scrape-uri=http://nginx/stub_status"]
    depends_on:
    - nginx


  # Prometheus service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - nextjs-app-instance1
      - redis

  # Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3004:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
